import React, { useEffect, useRef } from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { createStackNavigator } from '@react-navigation/stack';
import { Ionicons } from '@expo/vector-icons';
import { View, StyleSheet, Platform, Text, StatusBar, Dimensions, TouchableOpacity, Alert, Share, Modal, Pressable, Image } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
// import { BlurView } from '@react-native-community/blur';
import Animated, {
  useSharedValue,
  useAnimatedStyle,
  withSpring,
  withTiming,
  withSequence,
  withDelay,
  interpolate,
  Extrapolate,
  FadeInDown,
} from 'react-native-reanimated';
import { colors, spacing, borderRadius, shadows, typography, gradients, animations } from '../utils/theme';
import { useApp } from '../contexts/AppContext';

// Import screens
import DashboardScreen from '../screens/DashboardScreen';
import DashboardScreenSimple from '../screens/DashboardScreenSimple';
import TransactionsScreen from '../screens/TransactionsScreen';
import EditTransactionScreen from '../screens/EditTransactionScreen';
import EditCategoryScreen from '../screens/EditCategoryScreen';
import CategoriesScreen from '../screens/CategoriesScreen';
import BudgetScreen from '../screens/BudgetScreen';
import AlertsScreen from '../screens/AlertsScreen';
import SettingsScreen from '../screens/SettingsScreen';
import ReportScreen from '../screens/ReportScreen';
import AddTransactionModal from '../components/AddTransactionModal';
import ProfileScreen from '../screens/ProfileScreen';
import SetupScreen from '../screens/SetupScreen';

const Tab = createBottomTabNavigator();
const Stack = createStackNavigator();
const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

// Empty screen component for the Add tab
const EmptyScreen: React.FC = () => {
  return null;
};

// Modern Animated Header Component
const ModernHeader = ({ title, showBackButton = false, onBackPress, isDashboard = false, navigation, currentRoute }: { 
  title: string; 
  showBackButton?: boolean; 
  onBackPress?: () => void; 
  isDashboard?: boolean;
  navigation?: any;
  currentRoute?: string;
}) => {
  const { data } = useApp();
  const headerOpacity = useSharedValue(0);
  const headerTranslateY = useSharedValue(-50);

  useEffect(() => {
    headerOpacity.value = withTiming(1, { duration: animations.slow });
    headerTranslateY.value = withSpring(0, { damping: 15, stiffness: 100 });
  }, []);

  const animatedHeaderStyle = useAnimatedStyle(() => ({
    opacity: headerOpacity.value,
    transform: [{ translateY: headerTranslateY.value }],
  }));

  const generateQuickReport = () => {
    if (!data?.transactions) return 'No data available';
    
    const currentDate = new Date();
    const currentMonth = currentDate.getMonth();
    const currentYear = currentDate.getFullYear();
    
    const monthlyTransactions = data.transactions.filter(transaction => {
      const transactionDate = new Date(transaction.date);
      return transactionDate.getMonth() === currentMonth && 
             transactionDate.getFullYear() === currentYear;
    });
    
    const income = monthlyTransactions
      .filter(t => t.type === 'income')
      .reduce((sum, t) => sum + t.amount, 0);
    
    const expenses = monthlyTransactions
      .filter(t => t.type === 'expense')
      .reduce((sum, t) => sum + t.amount, 0);
    
    const balance = income - expenses;
    
    const formatCurrency = (amount: number) => {
      return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: data?.settings?.currency || 'USD',
        minimumFractionDigits: 0,
      }).format(amount);
    };
    
    let report = `📊 BUDGET SUMMARY - ${currentDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}\n\n`;
    report += `💰 INCOME: ${formatCurrency(income)}\n`;
    report += `💸 EXPENSES: ${formatCurrency(expenses)}\n`;
    report += `💵 BALANCE: ${formatCurrency(balance)}\n`;
    report += `📝 TRANSACTIONS: ${monthlyTransactions.length}\n\n`;
    report += `Generated by Budget Manager App`;
    
    return report;
  };

  const generateCSV = () => {
    if (!data?.transactions || data.transactions.length === 0) {
      return 'Date,Description,Category,Type,Amount\nNo transactions found';
    }
    
    const currentDate = new Date();
    const currentMonth = currentDate.getMonth();
    const currentYear = currentDate.getFullYear();
    
    const monthlyTransactions = data.transactions.filter(transaction => {
      const transactionDate = new Date(transaction.date);
      return transactionDate.getMonth() === currentMonth && 
             transactionDate.getFullYear() === currentYear;
    });
    
    if (monthlyTransactions.length === 0) {
      return 'Date,Description,Category,Type,Amount\nNo transactions for current month';
    }
    
    let csv = 'Date,Description,Category,Type,Amount\n';
    monthlyTransactions.forEach(transaction => {
      const date = new Date(transaction.date).toLocaleDateString();
      const description = (transaction.description || '').replace(/"/g, '""').replace(/,/g, ';');
      const category = (transaction.category || '').replace(/"/g, '""').replace(/,/g, ';');
      const type = transaction.type || 'unknown';
      const amount = transaction.amount || 0;
      
      csv += `${date},"${description}","${category}","${type}",${amount}\n`;
    });
    
    return csv;
  };

  const generatePDFContent = () => {
    if (!data?.transactions) return '';
    
    const currentDate = new Date();
    const currentMonth = currentDate.getMonth();
    const currentYear = currentDate.getFullYear();
    
    const monthlyTransactions = data.transactions.filter(transaction => {
      const transactionDate = new Date(transaction.date);
      return transactionDate.getMonth() === currentMonth && 
             transactionDate.getFullYear() === currentYear;
    });
    
    const income = monthlyTransactions
      .filter(t => t.type === 'income')
      .reduce((sum, t) => sum + t.amount, 0);
    
    const expenses = monthlyTransactions
      .filter(t => t.type === 'expense')
      .reduce((sum, t) => sum + t.amount, 0);
    
    const balance = income - expenses;
    
    const formatCurrency = (amount: number) => {
      return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: data?.settings?.currency || 'USD',
        minimumFractionDigits: 0,
      }).format(amount);
    };
    
    let pdfContent = `BUDGET MANAGER REPORT\n`;
    pdfContent += `Generated: ${currentDate.toLocaleDateString()}\n`;
    pdfContent += `Period: ${currentDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}\n\n`;
    
    pdfContent += `SUMMARY\n`;
    pdfContent += `-------\n`;
    pdfContent += `Total Income: ${formatCurrency(income)}\n`;
    pdfContent += `Total Expenses: ${formatCurrency(expenses)}\n`;
    pdfContent += `Net Balance: ${formatCurrency(balance)}\n`;
    pdfContent += `Total Transactions: ${monthlyTransactions.length}\n\n`;
    
    pdfContent += `TRANSACTIONS\n`;
    pdfContent += `------------\n`;
    pdfContent += `Date\t\tDescription\t\tCategory\t\tType\t\tAmount\n`;
    pdfContent += `----\t\t-----------\t\t--------\t\t----\t\t------\n`;
    
    monthlyTransactions.forEach(transaction => {
      const date = new Date(transaction.date).toLocaleDateString();
      const description = transaction.description;
      const category = transaction.category;
      const type = transaction.type;
      const amount = formatCurrency(transaction.amount);
      
      pdfContent += `${date}\t\t${description}\t\t${category}\t\t${type}\t\t${amount}\n`;
    });
    
    return pdfContent;
  };

  const handleShare = async () => {
    try {
      Alert.alert(
        'Export Options',
        'Choose export format:',
        [
          { text: 'Cancel', style: 'cancel' },
          {
            text: 'Text Report',
            onPress: async () => {
              const reportText = generateQuickReport();
              await Share.share({
                message: reportText,
                title: 'Budget Summary',
              });
            }
          },
          {
            text: 'CSV (Excel)',
            onPress: async () => {
              const csvContent = generateCSV();
              await Share.share({
                message: csvContent,
                title: 'Budget Data - Excel Format',
              });
            }
          },
          {
            text: 'PDF Format',
            onPress: async () => {
              const pdfContent = generatePDFContent();
              await Share.share({
                message: pdfContent,
                title: 'Budget Report - PDF Format',
              });
            }
          }
        ]
      );
    } catch (error) {
      Alert.alert('Error', 'Failed to share report');
    }
  };

  return (
    <Animated.View style={[styles.headerContainer, animatedHeaderStyle]}>
      <StatusBar barStyle="light-content" backgroundColor="transparent" translucent />
      <View style={styles.headerGradient}>
        <View style={styles.headerContent}>
          {/* Left Side - App Name (only for Dashboard) or Screen Title (for other screens) */}
          {isDashboard ? (
            <View style={styles.dashboardHeaderContainer}>
              <View style={styles.profileImage}>
                <Ionicons name="wallet" size={20} color={colors.white} />
              </View>
              <Text style={styles.userName}>BUDGET MANAGER</Text>
            </View>
          ) : (
            <View style={styles.screenTitleContainer}>
              <Text style={styles.headerTitle}>{title}</Text>
            </View>
          )}
          
          {/* Center - Screen Title (only for Dashboard) */}
          {isDashboard && title && (
            <View style={styles.titleContainer}>
              <Text style={styles.headerTitle}>{title}</Text>
            </View>
          )}
          
          {/* Right Side - Settings or Share */}
          <View style={styles.headerActions}>
            {currentRoute === 'Report' ? (
              <TouchableOpacity
                onPress={handleShare}
                style={styles.shareButton}
              >
                <View style={styles.shareIcon}>
                  <Ionicons 
                    name="share-outline" 
                    size={22} 
                    color={colors.white} 
                  />
                </View>
              </TouchableOpacity>
            ) : (
              <TouchableOpacity
                onPress={() => navigation?.navigate('Settings')}
                style={styles.settingsButton}
              >
                <View style={styles.settingsIcon}>
                  <Ionicons 
                    name="settings-outline" 
                    size={22} 
                    color={colors.white} 
                  />
                </View>
              </TouchableOpacity>
            )}
          </View>
        </View>
      </View>
    </Animated.View>
  );
};

// Modern Animated Tab Bar Component with Glassmorphism
const CustomTabBar = ({ state, descriptors, navigation }: any) => {
  const { profile } = useApp();
  const tabBarOpacity = useSharedValue(0);
  const tabBarTranslateY = useSharedValue(100);

  useEffect(() => {
    tabBarOpacity.value = withTiming(1, { duration: animations.slow });
    tabBarTranslateY.value = withSpring(0, { damping: 15, stiffness: 100 });
  }, []);

  const animatedTabBarStyle = useAnimatedStyle(() => ({
    opacity: tabBarOpacity.value,
    transform: [{ translateY: tabBarTranslateY.value }],
  }));

  return (
    <Animated.View style={[styles.tabBarContainer, animatedTabBarStyle]}>
      <View style={styles.tabBarGradient}>
        <View style={styles.tabBarContent}>
          {state.routes.map((route: any, index: number) => {
            const { options } = descriptors[route.key];
            const isFocused = state.index === index;

            const onPress = () => {
              const event = navigation.emit({
                type: 'tabPress',
                target: route.key,
                canPreventDefault: true,
              });

              if (!isFocused && !event.defaultPrevented) {
                navigation.navigate(route.name, route.params);
              }
            };

            const onLongPress = () => {
              navigation.emit({
                type: 'tabLongPress',
                target: route.key,
              });
            };

            let iconName: keyof typeof Ionicons.glyphMap;
            if (route.name === 'Dashboard') {
              iconName = isFocused ? 'wallet' : 'wallet-outline';
            } else if (route.name === 'Transactions') {
              iconName = isFocused ? 'receipt' : 'receipt-outline';
            } else if (route.name === 'Add') {
              iconName = isFocused ? 'add-circle' : 'add-circle-outline';
            } else if (route.name === 'Budget') {
              iconName = isFocused ? 'pie-chart' : 'pie-chart-outline';
            } else if (route.name === 'Categories') {
              iconName = isFocused ? 'grid' : 'grid-outline';
            } else if (route.name === 'Report') {
              iconName = isFocused ? 'bar-chart' : 'bar-chart-outline';
            } else if (route.name === 'Profile') {
              iconName = isFocused ? 'person' : 'person-outline';
            } else {
              iconName = 'help-outline';
            }

            return (
              <AnimatedTabItem
                key={route.key}
                route={route}
                iconName={iconName}
                isFocused={isFocused}
                onPress={onPress}
                onLongPress={onLongPress}
                index={index}
                profile={route.name === 'Profile' ? profile : null}
              />
            );
          })}
        </View>
      </View>
    </Animated.View>
  );
};

// Animated Tab Item Component
const AnimatedTabItem = ({ 
  route, 
  iconName, 
  isFocused, 
  onPress, 
  onLongPress, 
  index,
  profile
}: any) => {
  const scale = useSharedValue(1);
  const opacity = useSharedValue(0);
  const translateY = useSharedValue(20);

  useEffect(() => {
    opacity.value = withDelay(
      index * 100,
      withTiming(1, { duration: animations.normal })
    );
    translateY.value = withDelay(
      index * 100,
      withSpring(0, { damping: 15, stiffness: 100 })
    );
  }, []);

  const animatedItemStyle = useAnimatedStyle(() => ({
    opacity: opacity.value,
    transform: [
      { translateY: translateY.value },
      { scale: scale.value },
    ],
  }));

  const pressIn = () => {
    scale.value = withSpring(0.9, { damping: 15, stiffness: 200 });
  };

  const pressOut = () => {
    scale.value = withSpring(1, { damping: 15, stiffness: 200 });
  };

  return (
    <Animated.View style={[styles.tabItem, animatedItemStyle]}>
      <TouchableOpacity
        onPress={onPress}
        onLongPress={onLongPress}
        onPressIn={pressIn}
        onPressOut={pressOut}
        style={styles.tabItemTouchable}
        activeOpacity={0.8}
      >
        {route.name === 'Add' ? (
          <AnimatedAddButton iconName={iconName} isFocused={isFocused} />
        ) : (
          <AnimatedTabIcon 
            iconName={iconName} 
            isFocused={isFocused} 
            profile={route.name === 'Profile' ? profile : null}
          />
        )}
      </TouchableOpacity>
    </Animated.View>
  );
};



// Animated Add Button Component
const AnimatedAddButton = ({ iconName, isFocused }: any) => {
  const scale = useSharedValue(1);
  const rotation = useSharedValue(0);

  useEffect(() => {
    if (isFocused) {
      scale.value = withSpring(1.1, { damping: 15, stiffness: 100 });
      rotation.value = withSpring(360, { damping: 15, stiffness: 100 });
    } else {
      scale.value = withSpring(1, { damping: 15, stiffness: 100 });
      rotation.value = withSpring(0, { damping: 15, stiffness: 100 });
    }
  }, [isFocused]);

  const animatedStyle = useAnimatedStyle(() => ({
    transform: [
      { scale: scale.value },
      { rotate: `${rotation.value}deg` },
    ],
  }));

  return (
    <Animated.View style={[
      styles.addButtonContainer,
      isFocused && styles.addButtonFocused,
      animatedStyle
    ]}>
      <Ionicons 
        name={iconName} 
        size={isFocused ? 28 : 26} 
        color={isFocused ? colors.white : colors.textSecondary} 
      />
    </Animated.View>
  );
};

// Animated Tab Icon Component
const AnimatedTabIcon = ({ iconName, isFocused, profile }: any) => {
  const scale = useSharedValue(1);
  const opacity = useSharedValue(0.6);

  useEffect(() => {
    if (isFocused) {
      scale.value = withSpring(1.2, { damping: 15, stiffness: 100 });
      opacity.value = withTiming(1, { duration: animations.fast });
    } else {
      scale.value = withSpring(1, { damping: 15, stiffness: 100 });
      opacity.value = withTiming(0.6, { duration: animations.fast });
    }
  }, [isFocused]);

  const animatedStyle = useAnimatedStyle(() => ({
    transform: [{ scale: scale.value }],
    opacity: opacity.value,
  }));

  return (
    <Animated.View style={[
      styles.tabIconContainer,
      isFocused && styles.tabIconFocused,
      animatedStyle
    ]}>
      {profile && profile.avatarType === 'image' && profile.avatar ? (
        <Image 
          source={{ uri: profile.avatar }} 
          style={[
            styles.profileAvatar,
            { 
              width: isFocused ? 26 : 24, 
              height: isFocused ? 26 : 24,
              borderRadius: isFocused ? 13 : 12,
            }
          ]}
          resizeMode="cover"
        />
      ) : (
        <Ionicons 
          name={iconName} 
          size={isFocused ? 26 : 24} 
          color={isFocused ? colors.primary : colors.textSecondary} 
        />
      )}
    </Animated.View>
  );
};

// Tab Navigator Component
const TabNavigator: React.FC<{
  onMorePress: () => void;
}> = ({ onMorePress }) => {
  const { showAddModal, setShowAddModal } = useApp();

  return (
    <>
      <Tab.Navigator
        tabBar={(props) => <CustomTabBar {...props} />}
          screenOptions={({ route }) => ({
            header: ({ navigation, options }) => {
              const title = options.title || (route.name === 'Dashboard' ? '' : route.name);
              const isDashboard = route.name === 'Dashboard';
              return <ModernHeader title={title} isDashboard={isDashboard} navigation={navigation} currentRoute={route.name} />;
            },
          headerStyle: {
            backgroundColor: 'transparent',
            borderBottomColor: 'transparent',
            borderBottomWidth: 0,
            elevation: 0,
            shadowOpacity: 0,
          },
          headerTransparent: true,
          headerShadowVisible: false,
        })}
      >
        <Tab.Screen 
          name="Dashboard" 
          component={DashboardScreen}
          options={{ headerShown: false }}
        />
        <Tab.Screen 
          name="Transactions" 
          component={TransactionsScreen}
          options={{ headerShown: false }}
        />
        <Tab.Screen 
          name="Categories" 
          component={CategoriesScreen}
          options={{ 
            headerShown: false,
          }}
        />
        <Tab.Screen 
          name="Add" 
          component={EmptyScreen}
          options={{ 
            title: 'Add Transaction',
            tabBarLabel: 'Add',
          }}
          listeners={({ navigation }) => ({
            tabPress: (e) => {
              e.preventDefault();
              setShowAddModal(true);
            },
          })}
        />
        <Tab.Screen 
          name="Budget" 
          component={BudgetScreen}
          options={{ 
            headerShown: false,
          }}
        />
        <Tab.Screen 
          name="Report" 
          component={ReportScreen}
          options={{ 
            headerShown: false,
          }}
        />
        <Tab.Screen 
          name="Profile" 
          component={ProfileScreen}
          options={{ 
            headerShown: false,
          }}
        />
      </Tab.Navigator>
      
      <AddTransactionModal 
        visible={showAddModal} 
        onClose={() => setShowAddModal(false)} 
      />
    </>
  );
};


// Main App Navigator with Stack
const AppNavigator: React.FC = () => {
  const navigationRef = useRef<any>(null);

  return (
    <NavigationContainer ref={navigationRef}>
      <Stack.Navigator
        screenOptions={{
          headerShown: false,
        }}
        initialRouteName="MainTabs"
      >
        <Stack.Screen 
          name="MainTabs" 
        >
          {() => <TabNavigator onMorePress={() => {}} />}
        </Stack.Screen>
        <Stack.Screen 
          name="EditTransaction" 
          component={EditTransactionScreen}
          options={{
            headerShown: false,
          }}
        />
        <Stack.Screen 
          name="EditCategory" 
          component={EditCategoryScreen}
          options={{
            headerShown: false,
          }}
        />
        <Stack.Screen 
          name="Report" 
          component={ReportScreen}
          options={{
            headerShown: false,
          }}
        />
        <Stack.Screen 
          name="Categories" 
          component={CategoriesScreen}
          options={{
            headerShown: false,
          }}
        />
        <Stack.Screen 
          name="Alerts" 
          component={AlertsScreen}
          options={{
            headerShown: false,
            presentation: 'modal',
            cardStyle: { backgroundColor: 'transparent' },
            cardOverlayEnabled: true,
          }}
        />
        <Stack.Screen 
          name="Settings" 
          component={SettingsScreen}
          options={{
            headerShown: false,
          }}
        />
        <Stack.Screen 
          name="Profile" 
          component={ProfileScreen}
          options={{
            headerShown: false,
          }}
        />
        <Stack.Screen 
          name="Setup" 
          component={SetupScreen}
          options={{
            headerShown: false,
          }}
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

const styles = StyleSheet.create({
  // Header Styles
  headerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
    elevation: 10,
    backgroundColor: colors.background,
    ...shadows.lg,
  },
  headerGradient: {
    paddingTop: Platform.OS === 'ios' ? 44 + spacing.xs : (StatusBar.currentHeight || 0) + spacing.xs,
    paddingBottom: 12,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.background,
    ...shadows.lg,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 44,
  },
  dashboardHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  profileImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.sm,
  },
  userName: {
    fontSize: 16,
    color: colors.white,
    fontWeight: 'bold',
    marginLeft: spacing.sm,
  },
  screenTitleContainer: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  titleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.white,
    letterSpacing: 0.3,
    textAlign: 'center',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: 1,
  },
  settingsButton: {
    padding: spacing.xs,
  },
  settingsIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  shareButton: {
    padding: spacing.xs,
  },
  shareIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  
  // Tab Bar Styles
  tabBarContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    ...shadows.lg,
  },
  tabBarGradient: {
    paddingBottom: Platform.OS === 'ios' ? 16 : 8,
    paddingTop: 4,
    borderTopLeftRadius: borderRadius.lg,
    borderTopRightRadius: borderRadius.lg,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
    backgroundColor: colors.surface,
  },
  tabBarContent: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: spacing.sm,
    minHeight: 50,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xs,
  },
  tabItemTouchable: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.xs,
    borderRadius: borderRadius.md,
  },
  tabIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  tabIconFocused: {
    backgroundColor: colors.primary + '20',
    borderWidth: 1,
    borderColor: colors.primary + '40',
  },
  profileAvatar: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.primary + '40',
  },
  addButtonContainer: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.border,
    ...shadows.sm,
  },
  addButtonFocused: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    ...shadows.lg,
  },

});

export default AppNavigator;
